# Generated by Django 5.2.12 on 2026-03-05 03:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('editorial', models.CharField(blank=True, max_length=200)),
                ('anio_publicacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('edicion', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('en_reparacion', 'En Reparación'), ('perdido', 'Perdido')], default='disponible', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=50, verbose_name='Estante/Ubicación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autores', models.ManyToManyField(related_name='libros', to='libros.autor')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='libros.categoria')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
    ]
